### ISSUE TITLE
updating keynote speakers content

### ISSUE THREAD

**Issue by Chamodi88** [erasmus-mundus-geotech-master/Geomundus2019#100]
insert description for Laura Diaz in the keynote speakers section. Find the description here
https://docs.google.com/document/d/1TApyargyfiw0fkHyC_sLlVnL1vXa7GywFYRzzRX8iBw/edit

**Comment by ismailsunni** [comment]
hi, @Chamodi88 do you have a good image/photo for her to put in the website?

**Comment by Chamodi88** [comment]
Nop. we don't have any other photo. That's the one she shared with us.
