### ISSUE TITLE
Update the website

### ISSUE THREAD

**Issue by Chamodi88** [erasmus-mundus-geotech-master/Geomundus2019#106]
paper and poster submission is now closed. please update the website accordingly.

**Comment by ismailsunni** [comment]
hi @Chamodi88 can you suggest some text or announcement in the submission section?

for example, How will the accepted submission be contacted or announced?

You can see the proposed update in https://fix-106-geomundus.netlify.com

**Comment by Chamodi88** [comment]
refer this  #107

**Comment by ismailsunni** [comment]
Hi @Chamodi88 update, please check https://fix-106-geomundus.netlify.com/ to see the change. If you think it's ok, I will merge the change and the web team will update the live site.

**Comment by Chamodi88** [comment]
It looks fine. please highlight "October 21st, 2019" .

**Comment by ismailsunni** [comment]
@Chamodi88 
I have highlighted it and merged my PR.

@neogeomat please update the live site.
