### ISSUE TITLE
add esri logo to sponsor page

### ISSUE THREAD

**Issue by sinki-blau** [erasmus-mundus-geotech-master/Geomundus2019#110]
add esri logo to sponsor page

**Comment by ismailsunni** [comment]
@sinki-blau can you tell me which logo? and in which location? see below

![image](https://user-images.githubusercontent.com/1421861/67762451-c6697c00-fa45-11e9-8803-8799e37709e4.png)

**Comment by neogeomat** [comment]
Do we have AGILE this year?

**Comment by sinki-blau** [comment]
Hiya,
we have only secured the funding from esri this year - and also its a
different company - its esri inc.
but we still waiting for the logo from the company - just fyi about the
update!
Thanks :D

**Comment by sinki-blau** [comment]
Hi guys so here is the esri logo, we also just secured the sponsorship from agile.
so full name of esri is Esri Inc. 
and for agile please use the logo from last year. 
Thanks guys!!

![image](https://user-images.githubusercontent.com/48051970/68044350-127b2180-fccf-11e9-9b1d-aff2dfcee662.jpeg)
![Esri_Corp_Logo_10,_4C white box](https://user-images.githubusercontent.com/48051970/68044351-1313b800-fccf-11e9-8a3f-705bd7bbe909.JPG)

**Comment by ismailsunni** [comment]
Hi @sinki-blau 
I have updated with your Esri logo and it lives now.
Please check and let me know if you think it's ok or not.

**Comment by sinki-blau** [comment]
Hi @ismailsunni  can you change esris name to" esri Inc. "
Thanks

**Comment by ismailsunni** [comment]
@sinki-blau with lower case "esri Inc"? Or "ESRI Inc" Just to make sure.

**Comment by ismailsunni** [comment]
@sinki-blau I use ESRI Inc. since it looks better. Let me know which one you prefer. It's already push to live web.

**Comment by sinki-blau** [comment]
Hey sorry didnt get to check email
Esri Inc. Please!
Thanksss

**Comment by ismailsunni** [comment]
@sinki-blau done! hopefully the last one. Please check for making sure :)
