### ISSUE TITLE
Update grantholders winners

### ISSUE THREAD

**Issue by violetasdev** [erasmus-mundus-geotech-master/Geomundus2019#116]
Date: 08-Nov- 2019

Grantholders winners:

"Congratulations to the 2019 Geomundus Grantholders"

- Dennis P. Dizon
- Shangharsha Thapa
- Nianhua Liu

**Comment by ismailsunni** [comment]
@violetasdev 
can you give more information, for example, their paper's submission title, and where does the grant come from? Like in 2018 version one.
Or we don't need to mention that?

**Comment by violetasdev** [comment]
Here is the information Sunni,

1. Dennis Dizon, Title: Spatial Autocorrelation and Crosscorrelation Analysis of Voting Participation in the Philippines. Technical University of Munich. Germany

2. Sapkota Sujan, *Thapa Shangharsha*, Parajuli Pukar, Bhatta Raj Nabin, Title: Estimation of Soil Deposition in Section of Punyamata River, Nepal, due to Flooding Using Unmanned Aerial Vehicle. Lund University, Sweden

3. Nianhua Liu, Man Xiao, Xin Xu, Xuezhang Li, Qian Shi, Title: Environmental Detection and Management Based on Multi-source Remote Sensing Data from Baiyangdian Lake. Sun Yat-Sen University . P.R. China
