### ISSUE TITLE
updating conference agenda

### ISSUE THREAD

**Issue by Chamodi88** [erasmus-mundus-geotech-master/Geomundus2019#123]
please make changes on the program according to 
https://docs.google.com/spreadsheets/d/1uPclg3oJ0IoIogbi5w3yn0RsPGlPZJhkMDEFfoQ91hw/edit#gid=723587736

**Comment by ismailsunni** [comment]
Hi @Chamodi88 
Question:
1. Alumni Voice Session will be from 15:15 to 16:15? Is that correct? It's more than the keynote speaker (1 hour vs 45 minutes)
2. No poster session?
3. No more detail information on what and where is the "Networking session with food and drinks?

**Comment by itzahs** [comment]
1. Yes, they are 3 people, tentatively 4 sharing their experience. It's like the career development but alumnis! Time to ask for "what life after the master is".
2. Poster session spot was given to "Here Maps presentation". We have only 2 posters and people can see them during the coffee breaks.
3. In the meantime there's the possibility to change to speedgeeking, need to do a poll first. But, Networking Session is fine by now. Might be or not updated later. It will be in UJI grounds.

**Comment by Chamodi88** [comment]
please update the workshop 4 details also.

**Comment by ismailsunni** [comment]
@Chamodi88 done. All changes are live now in the geomundus.org.
