### ISSUE TITLE
Change in workshop speakers

### ISSUE THREAD

**Issue by itzahs** [erasmus-mundus-geotech-master/Geomundus2019#129]
Please change here:
Workshop 4: Retrieve and process satellite images time series towards data analysis in R
Facilitator: Mehdi Moradi and Unai Perez Goya, Departamento de Estadística e Investigación Operativa, Universidad Pública de Navarra

With
Mehdi Moradi and Manuel Montesino-SanMartin, those are the final ones,

thank you

**Comment by ismailsunni** [comment]
Done.
