### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by violetasdev** [erasmus-mundus-geotech-master/Geomundus2019#13]
Change the text to be more professional and welcoming when asking for sponsors.

> Geomundus is looking for sponsors and partners from all the spatial, technological, public or private, scientific, governmental, academic and more fields. We will be thrilled to have all the support and participation in this international event.
> 
>Please feel free to contact the budget team at budget@geomundus.org for more information on how to help and contribute! We will glad to hear all the wishes to sponsor the 2019 GeoMundus conference and future years.

Additionally, it is also an improvement to list past sponsors. Having them there is evidence of others believing in the project and making a statement. Most companies rely on the name of other companies to evaluate their participation.

**Comment by neogeomat** [comment]
completed
