### ISSUE TITLE
Add Here maps presentation title in agenda

### ISSUE THREAD

**Issue by Chamodi88** [erasmus-mundus-geotech-master/Geomundus2019#130]
Title : From Maps to Location Services

**Comment by Chamodi88** [comment]
Pablo Lampón, Title : From Maps to Location Services

**Comment by ismailsunni** [comment]
Hi @Chamodi88 
Should I mention "HERE Technology" also on the agenda?

Or like this:
```
HERE Technology Presentation: Pablo Lampón
[Hidden, and will be shown when it clicked] 
Title : From Maps to Location Services
```

Or just like this:
```
Presentation by Pablo Lampón, Title : From Maps to Location Services
(without expanded part)
```

**Comment by ismailsunni** [comment]
Or like this:
```
HERE Maps Presentation: Pablo Lampón, Title : From Maps to Location Services
```

**Comment by Chamodi88** [comment]
I think this way is better. 
HERE Technology Presentation: Pablo Lampón
[Hidden, and will be shown when it clicked] 
Title : From Maps to Location Services

**Comment by ismailsunni** [comment]
Done @Chamodi88
