### ISSUE TITLE
Conference Agenda

### ISSUE THREAD

**Issue by itzahs** [erasmus-mundus-geotech-master/Geomundus2019#133]
In the conference agenda, please modify the following: 
**12:20:00 - HERE Technologies**

Workshop 3: (to be updated soon)
Facilitator: **Jonathan** A. Gonzalez, department of **Mathematics**

Thank you

**Comment by ismailsunni** [comment]
@ItzaHernandez 
Update:
![image](https://user-images.githubusercontent.com/1421861/69033074-692a7000-09de-11ea-8164-0c09709a08d9.png)
![image](https://user-images.githubusercontent.com/1421861/69033094-72b3d800-09de-11ea-8c32-512ee6cce5e8.png)
