### ISSUE TITLE
updating conference agenda

### ISSUE THREAD

**Issue by Chamodi88** [erasmus-mundus-geotech-master/Geomundus2019#134]
update the description of here map presentation.

Throughout history, location has played a key role in the development and progress of people and societies.

During this session, HERE will show how are they focused on the concept of location and the potential it has to radically improve the way we do business, the way we get around and the way we live, shaping the future by redefining what was formerly known as a map.

We will discover anecdotes and curiosities about mapping technology: From the beginning, when they started digitizing maps to pioneer in-car navigation systems, to the present, representing living three-dimensional maps that grow upwards, breathing with layers of information and insights.

This representation of reality will maximize the possibilities of the different industries to create services and developments that enable people and objects to move, interact and live faster, safer and in a more efficient way than ever before.

**Comment by ismailsunni** [comment]
Result: 

![image](https://user-images.githubusercontent.com/1421861/69318423-7002ee00-0c3d-11ea-8ef4-2e84f2c837bb.png)
