### ISSUE TITLE
Repeated issue: please remove Artificial Inteligence theme

### ISSUE THREAD

**Issue by itzahs** [erasmus-mundus-geotech-master/Geomundus2019#22]
In what is Geomundus:

This year’s GeoMundus will also explore the use of Artificial Intelligence in these fields, highlighting the research that pushes the boundaries of geospatial analysis through machine learning, with specific keynote, workshop, and presentations.

In why Geomundus:

This year, one of the topic of focus, ‘Artificial Intelligence in Geoinformatics’ will give participants the chance to learn about technological advancements of AI, research activities on it and it’s applications on geospatial technologies in today’s world.

**Comment by neogeomat** [comment]
removed
