### ISSUE TITLE
Same zoom in pictures

### ISSUE THREAD

**Issue by violetasdev** [erasmus-mundus-geotech-master/Geomundus2019#28]
The pictures of each one of the members should have the same zoom. It is needed to decide Face or Body zoom.

Some of the team members face are too small compared to others.

**Comment by ismailsunni** [comment]
@al383353 can you fix it? Let's use face zoom since most photos are already in face zoom.

**Comment by senait8991** [comment]
> @al383353 can you fix it? Let's use face zoom since most photos are already in face zoom.

All the photos have different size and I have used the same size for all, now I will not do it, let me try at the weekend.

**Comment by senait8991** [comment]
> > @al383353 can you fix it? Let's use face zoom since most photos are already in face zoom.
> 
> All the photos have different size and I have used the same size for all, now I will not do it, let me try at the weekend.

There are 5 students with body zoom.

**Comment by ismailsunni** [comment]
Fixed in #41
