### ISSUE TITLE
Reupload Muenster university logo

### ISSUE THREAD

**Issue by violetasdev** [erasmus-mundus-geotech-master/Geomundus2019#33]
In section Partners, Muenster University logo is broken also the circle div needs to be aligned to the other ones. 

The link for this image should redirect to the ifgi website link.

**Comment by neogeomat** [comment]
The muenster logo is elongated whereas others are square and it does not fit with the other logos and difficult to align.

**Comment by neogeomat** [comment]
Replaced with german version which is square.
