### ISSUE TITLE
The text in the "Programme" is not aligned

### ISSUE THREAD

**Issue by hasan9206** [erasmus-mundus-geotech-master/Geomundus2019#40]
The program for the conference is not aligned in the three tabs, The gap between the "Time" and "Description" sections increases in each date.

_Program of the first day_
![image](https://user-images.githubusercontent.com/7081695/57090865-19b57880-6d08-11e9-9b31-e61cdc9c125e.png)

_Program of the last day_
![image](https://user-images.githubusercontent.com/7081695/57090909-39e53780-6d08-11e9-966c-e44777871e5a.png)

**Comment by itzahs** [comment]
we need to complete this task

**Comment by neogeomat** [comment]
This is a bug in the framework and present in the previous years too. This gets fixed when the description is long enough to overflow into 2nd line.

**Comment by GithubSom** [comment]
CSS accordion(s) in the Programme section can be currently filled up by "Will be updated soon" type of sentences, till the sections have finalized statements; rather than keeping it active with BLANK information.

**Comment by GithubSom** [comment]
> This is a bug in the framework and present in the previous years too. This gets fixed when the description is long enough to overflow into 2nd line.

Is there any option to get rid of the bottom EXTRA Blank space for the program section (it was also a bug in the previous year).

**Comment by neogeomat** [comment]
@GithubSom this space? ![image](https://user-images.githubusercontent.com/2562658/59206408-89434100-8bad-11e9-8d98-2728e31fb378.png)
