### ISSUE TITLE
Pictures of Castellón de da Plana

### ISSUE THREAD

**Issue by vicetang** [erasmus-mundus-geotech-master/Geomundus2019#42]
Provide more pictures of the city and the university and display in slide show.

![pic](https://user-images.githubusercontent.com/45716859/57180181-70e15780-6e86-11e9-9f02-89c952d7b344.png)

**Comment by vicetang** [comment]
Also making sure they have the same proportions and keep centrally alligned with **class="6u$ 12u$(medium)"**

**Comment by tinabaidar13** [comment]
There are four pictures displayed in a slide show including university's picture. Do you mean we need to add more pictures?

**Comment by vicetang** [comment]
By the time I wrote this comment there was only one picture and no slideshow. It is nice now.

**Comment by ismailsunni** [comment]
@vicetang so, all is good? If so, I am closing this issue :)
