### ISSUE TITLE
Geomundus history videos broken

### ISSUE THREAD

**Issue by violetasdev** [erasmus-mundus-geotech-master/Geomundus2019#43]
Section for Geomundus history is broken. Check with PR team if we have the Youtube channel updated to connect directly.

**Comment by neogeomat** [comment]
Video is working in mine.

**Comment by neogeomat** [comment]
Working in others too.

**Comment by violetasdev** [comment]
![image](https://user-images.githubusercontent.com/3913942/57223152-6ac5b500-7005-11e9-85a6-53bb03b63b75.png)

**Comment by violetasdev** [comment]
Not working on mine. This section has to works independently of the affiliation to Facebook
