### ISSUE TITLE
Geomundus History Video doesnot play for users not logged into facebook.

### ISSUE THREAD

**Issue by neogeomat** [erasmus-mundus-geotech-master/Geomundus2019#46]
WIth reference to #43. Currently  the video is streaming from Facebook. Users who are not logged in to facebook cannot get the video because of Facebook restrictions. Consult with PR team for a publicly accessible video.

**Comment by neogeomat** [comment]
#43

**Comment by itzahs** [comment]
Video uploaded to youtube account and available in: https://www.youtube.com/watch?v=1l--VBTPv_Y&t=13s
