### ISSUE TITLE
Hotels offer

### ISSUE THREAD

**Issue by violetasdev** [erasmus-mundus-geotech-master/Geomundus2019#56]
Add more suggestions to the hotels per privacy concerns for the keynote speakers hotel and offer other participants to have more options

Local team meeting to get the information (already informed)

**Comment by ismailsunni** [comment]
No updates from Local team about the hotels until now.

**Comment by tinabaidar13** [comment]
We have decided to remove hotel options from the website. So please remove the accomodation icon!
