### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by itzahs** [erasmus-mundus-geotech-master/Geomundus2019#63]
The registration period is now **open**.

Add on open the link to the google form. 

https://forms.gle/8Go4n5xsMApyR1ci8

**Comment by vicetang** [comment]
Cancel this update. The registration will only be open next week, when we are sure that when finishing the form the confirmation e-mail of geomundus registration is sent to the participant.

**Comment by itzahs** [comment]
Please add the link to the form in the geomundus website @neogeomat

**Comment by ismailsunni** [comment]
@ItzaHernandez 
Is this ok?

![image](https://user-images.githubusercontent.com/1421861/58420823-9da41b80-808e-11e9-9f2b-555e1a572a65.png)

**Comment by ismailsunni** [comment]
@vicetang said to hold the links update
