### ISSUE TITLE
Improvement text "What is Geomundus"

### ISSUE THREAD

**Issue by violetasdev** [erasmus-mundus-geotech-master/Geomundus2019#7]
GeoMundus is a free international symposium organized by the students from the Erasmus Mundus Master's of Science in Geospatial Technologies. The conference aims to share cutting-edge scientific research, knowledge, and skills in the fields of Geospatial Technologies, Geoinformatics, and Geosciences, including but not limited to geographic information systems and sciences, spatial cognition, geography, and spatial data sciences. This year’s GeoMundus will also explore the use of Artificial Intelligence in these fields, highlighting the research that pushes the boundaries of geospatial analysis through machine learning, with specific keynotes speakers, workshop, and presentations. Please see the Programme Section for more detail information.

**Comment by neogeomat** [comment]
This is old content.

**Comment by neogeomat** [comment]
Last years theme has been purged and uploaded.
