### ISSUE TITLE
Improvement text "Why Geomundus"

### ISSUE THREAD

**Issue by violetasdev** [erasmus-mundus-geotech-master/Geomundus2019#8]
> GeoMundus is an opportunity to learn about and share scientific research, knowledge, and skills with other students and researchers of all things ‘Geo’. This year, one of the topics of focus, ‘Artificial Intelligence in Geoinformatics’ will give participants the chance to learn about technological advancements of AI, research activities on it and it is applications on geospatial technologies in today’s world. GeoMundus is unique, featuring workshops where participants can experience first-hand the future of the field as well as a career session specially designed for students interested in a geospatial career.

**Comment by vicetang** [comment]
We agreed we will not have a focus topic approach otherwise that may cause some restrictions.

**Comment by violetasdev** [comment]
True. I improve the grammar of the text in this section. A better /broad approach could be: 

> GeoMundus is an opportunity to learn about and share scientific research, knowledge, and skills with other students and researchers of all things ‘Geo’. Every year it will give participants the chance to learn about technological advancements of GI, research activities and applications on geospatial technologies in today’s world. GeoMundus is unique, featuring workshops where participants can experience first-hand the future of the field as well as a career session specially designed for students interested in a geospatial career.
