### ISSUE TITLE
DEADLINE: 03.Jun.2019 // Improve text in submission document templates

### ISSUE THREAD

**Issue by violetasdev** [erasmus-mundus-geotech-master/Geomundus2019#80]
> Here you can find the documentation guidelines for your submission:
> 
> Download Abstract guidelines (PDF/DOC)
> Dowload template for Abstract (PDF/DOC)
> Download Poster guidelines (PDF/DOC)

The different formats must be available on each one of the links listed above

**Comment by neogeomat** [comment]
It was decided to put drive link in read-only mode.

**Comment by neogeomat** [comment]
#83

**Comment by neogeomat** [comment]
Following the discussion on WhatsApp,  #79 has been approved.

**Comment by GithubSom** [comment]
Respective Google Docs have been updated.
Please find the Updated DOCX and PDF files here: 
https://drive.google.com/drive/folders/1IIujmchrf6aZ4uwrTBDXPpWw2ycr9tXc?usp=sharing
Please update the Downloadable files from the above-mentioned links.
