### ISSUE TITLE
call for paper  and posters

### ISSUE THREAD

**Issue by Chamodi88** [erasmus-mundus-geotech-master/Geomundus2019#83]
1. remove unnecessary bold effect in text. refer https://docs.google.com/document/d/18HqzoRQvcWZiX5Af7LnE28fEXVWGAH4RFMLsG7RMfnY/edit
2. the sentence "  The submission period for short papers and posters is now OPEN." should be separated as in the google doc. 

3. Put the sentence "Please note that GeoMundus does not provide invitations and does not support Visa Processes." in the right place as the google doc

4. " Submit of short paper (Here) " must be eye catching rather than a hyperlink. If possible design buttons for that

5. Guidelines and templates are not read-only. May be change it so that DOC/PDF is downloaded when clicking.

**Comment by itzahs** [comment]
Yes, and also last year they had a more appealing desing for submitting. I think two of these boxes are required:

![button](https://user-images.githubusercontent.com/50157492/58761762-f6206080-8547-11e9-9a56-975b24c053fb.jpg)

**Comment by neogeomat** [comment]
5. #79

**Comment by neogeomat** [comment]
buttons #86
