### ISSUE TITLE
Keynote Speakers

### ISSUE THREAD

**Issue by itzahs** [erasmus-mundus-geotech-master/Geomundus2019#85]
UPDATE

Add new section (keep past keynote speakers section)
2019 Keynote Speakers 

We are excited to have two confirmed keynote speakers sharing their expertise at our conference. Please visit their personal websites to find out more about them.

https://docs.google.com/document/d/1TApyargyfiw0fkHyC_sLlVnL1vXa7GywFYRzzRX8iBw/edit#

**Comment by GithubSom** [comment]
White background for Ms. Monica Wachowicz in the Past Keynote speakers section requires adjustment. 
The image size might be reduced to keep all the past keynote speakers image size inside the white background UNIFORM.

**Comment by itzahs** [comment]
Please add the "We are excited to have two keynotes speakers **CONFIRMED**" this confirmed means that we are expecting more and not just two, can you add it please 🙏🏽

**Comment by itzahs** [comment]
Check again the link, programme team just made an update to have Tim Sutton also in the website.
It would be the best to leave all three CONFIRMED keynote speakers ready before holidays!

Thank you! :D

**Comment by itzahs** [comment]
Please is important to leave all the THREE keynote speakers CONFIRMED in the live website before going on holidays! Thank you! :D

**Comment by neogeomat** [comment]
> White background for Ms. Monica Wachowicz in the Past Keynote speakers section requires adjustment.
> The image size might be reduced to keep all the past keynote speakers image size inside the white background UNIFORM.

Changing image size had no effect.
