### ISSUE TITLE
Add information in home page.

### ISSUE THREAD

**Issue by neogeomat** [erasmus-mundus-geotech-master/Geomundus2019#87]
Three best paper submissions from students will be awarded travel grants. Submit your paper here!

**Comment by GithubSom** [comment]
Update paragraph "What is Geomundus"
"GeoMundus is a free international symposium organized by the students....."
1. Symposium to be replaced by "Conference".
2. Organized by the students " for the students" to be added.

**Comment by GithubSom** [comment]
Three best paper submissions from students will be awarded travel grants. 
Submit your paper HERE!
Here will be the link to the page "Submission".

**Comment by ismailsunni** [comment]
@GithubSom 

> Update paragraph "What is Geomundus"
> "GeoMundus is a free international symposium organized by the students....."
> 
> Symposium to be replaced by "Conference".
> Organized by the students " for the students" to be added.

Can you put the whole sentence? There is 
> What is GeoMundus?
GeoMundus is a free international symposium organized by the students from the Erasmus Mundus Master's of Science in Geospatial Technologies. 

where should I put the "for the students"? If before the Erasmus Mundus... it will be strange since it's only for Erasmus student.

**Comment by GithubSom** [comment]
My suggestion is: 
GeoMundus is a free international conference organized by the students for the students. The organizing committee is the group of Erasmus Mundus Master's of Science in Geospatial Technologies students.
But please wait for other comments too.

**Comment by itzahs** [comment]
I like it Som, just one suggestion:
GeoMundus is a free international conference organized **by students for students**. The organizing committee is the students from the Erasmus Mundus Master's of Science in Geospatial Technologies.

Please update the live website before leaving on holidays! And remember to add to the home page:
Three best paper submissions from students will be awarded travel grants.
Submit your paper HERE!
