### ISSUE TITLE
About Us Image Background

### ISSUE THREAD

**Issue by GithubSom** [erasmus-mundus-geotech-master/Geomundus2019#88]
The white background of 2019 team members should be of UNIFORM size.

**Comment by itzahs** [comment]
Please also change symposium for conference
![image](https://user-images.githubusercontent.com/50157492/58944627-88ac4400-8782-11e9-9c67-8c9a5fbf2cfc.png)

**Comment by ismailsunni** [comment]
Hmm, it needs a lot of time since we need to resize all of the images to have the same aspect ratio.
Can you give me a hand @al383353 ?

**Comment by senait8991** [comment]
> Hmm, it needs a lot of time since we need to resize all of the images to have the same aspect ratio.
> Can you give me a hand @al383353 ?

shall I resize the the images and send you?
