### ISSUE TITLE
Promotional video

### ISSUE THREAD

**Issue by neogeomat** [erasmus-mundus-geotech-master/Geomundus2019#90]
PR team mentioned about promotional video.

**Comment by itzahs** [comment]
The promotional video is here: https://www.youtube.com/watch?v=iE3QapLTNuM but is mainly used for social media.

**Comment by neogeomat** [comment]
Any Suggestion on which place to put it?

**Comment by itzahs** [comment]
Please place it in the section: Who should participate in GeoMundus 2019? just after the text.

Thank you for all the updates!

**Comment by bclroger** [comment]
.
