### ISSUE TITLE
Dinner Location

### ISSUE THREAD

**Issue by mfcamargoh** [erasmus-mundus-geotech-master/Geomundus2019#95]
Cervecería Gambrinus
Location: C/ Prim, 12 - Plaza del Juez Borrull Castellón de la Plana - 12003
https://www.gambrinus.es/content/cervecer%C3%ADa-gambrinus-borrull-castell%C3%B3n
Telephone: 964 22 99 00 / 607115523 Vicente
Email: info@beerandfood.es

**Comment by neogeomat** [comment]
What is the meaning of vicente in telephone
